@extends('layouts.app')
@section('content')
<div class="flex items-center justify-between mb-6"><div><h1 class="text-2xl font-bold">Website Diagnostic</h1><p class="text-slate-500">{{ $website->name }} — {{ $website->url }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('websites.recheck',$website) }}">@csrf<button class="bg-blue-600 text-white rounded-lg px-4 py-2">Recheck Now</button></form><a target="_blank" href="{{ $website->url }}" class="border rounded-lg px-4 py-2">Open Website</a></div></div>
<div class="grid md:grid-cols-4 gap-4 mb-6"><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Status</div><div class="text-2xl font-bold">{{ strtoupper($website->status) }}</div></div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">HTTP</div><div class="text-2xl font-bold">{{ $website->http_code ?: '—' }}</div></div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Response</div><div class="text-2xl font-bold">{{ $website->response_time_ms ? $website->response_time_ms.' ms' : '—' }}</div></div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Security</div><div class="text-2xl font-bold">{{ strtoupper($website->security_status ?: 'unknown') }}</div></div></div>
<div class="grid lg:grid-cols-2 gap-6"><div class="bg-white border rounded-xl p-5"><h2 class="font-bold text-lg mb-3">What is the problem?</h2><p class="font-semibold mb-2">{{ $diagnostics['likely'] }}</p><div class="text-sm text-slate-600">{{ $diagnostics['error'] ?: 'No current error message.' }}</div><div class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="p-3 bg-slate-50 rounded-lg">DNS: <strong>{{ $diagnostics['dns_ok'] ? 'OK' : 'FAILED' }}</strong></div><div class="p-3 bg-slate-50 rounded-lg">SSL: <strong>{{ $diagnostics['ssl']['ok'] ? 'OK' : 'CHECK' }}</strong></div></div></div>
<div class="bg-white border rounded-xl p-5"><h2 class="font-bold text-lg mb-3">Quick Actions</h2><div class="space-y-2"><form method="POST" action="{{ route('websites.recheck',$website) }}">@csrf<button class="w-full text-left p-3 rounded-lg bg-blue-50 text-blue-700">🔄 Recheck website now</button></form><form method="POST" action="{{ route('websites.security',$website) }}">@csrf<button class="w-full text-left p-3 rounded-lg bg-fuchsia-50 text-fuchsia-700">🛡 Run server file security scan</button></form><a target="_blank" href="{{ $website->url }}" class="block p-3 rounded-lg bg-slate-50">🌐 Open website</a><a href="{{ route('websites.logs',$website) }}" class="block p-3 rounded-lg bg-slate-50">📋 View monitoring history</a></div></div></div>
@if($website->security_findings)<div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">🛡 Security Findings</h2>@foreach($website->security_findings as $f)<div class="border rounded-lg p-3 mb-2 text-sm"><strong>{{ $f['reason'] ?? 'Suspicious indicator' }}</strong><div>Pattern: <code>{{ $f['pattern'] ?? '—' }}</code></div>@if(isset($f['file']))<div>File: <code>{{ $f['file'] }}</code></div>@endif</div>@endforeach</div>@endif
<div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">🛡 Security Posture</h2><div class="text-3xl font-bold mb-2">{{ $diagnostics['security_score'] ?? '—' }}<span class="text-sm text-slate-500"> / 100</span></div><p class="text-sm text-slate-500 mb-4">This is a heuristic security posture score, not a malware verdict.</p><div class="grid md:grid-cols-2 gap-2 text-xs">@foreach($diagnostics['security_headers'] ?? [] as $k=>$v)<div class="p-2 rounded bg-slate-50"><strong>{{ $k }}</strong><div class="break-all text-slate-500">{{ $v }}</div></div>@endforeach</div></div><div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">SSL Information</h2><pre class="text-xs whitespace-pre-wrap">{{ json_encode($diagnostics['ssl'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div>
@endsection
