@extends('layouts.app')
@section('content')
<div class="flex items-center justify-between mb-6"><div><h1 class="text-2xl font-bold">Website Diagnostic</h1><p class="text-slate-500">{{ $website->name }} — {{ $website->url }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('websites.recheck',$website) }}">@csrf<button class="bg-blue-600 text-white rounded-lg px-4 py-2">Recheck Now</button></form><form method="POST" action="{{ route('websites.baseline',$website) }}" onsubmit="return confirm('Capture a NEW trusted baseline from the current homepage and files? Only do this when the website is in a known-good state.')">@csrf<button class="bg-emerald-600 text-white rounded-lg px-4 py-2">📸 Capture Trusted Baseline</button></form><a target="_blank" href="{{ $website->url }}" class="border rounded-lg px-4 py-2">Open Website</a></div></div>
<div class="grid md:grid-cols-4 gap-4 mb-6"><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Status</div><div class="text-2xl font-bold {{ $website->status==='suspicious' ? 'text-fuchsia-700' : '' }}">{{ strtoupper($website->status) }}</div>@if($diagnostics['previous_status'])<div class="text-xs text-slate-500">Previous: {{ strtoupper($diagnostics['previous_status']) }}</div>@endif</div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">HTTP</div><div class="text-2xl font-bold">{{ $website->http_code ?: '—' }}</div></div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Response</div><div class="text-2xl font-bold">{{ $website->response_time_ms ? $website->response_time_ms.' ms' : '—' }}</div></div><div class="bg-white border rounded-xl p-4"><div class="text-sm text-slate-500">Security</div><div class="text-2xl font-bold">{{ strtoupper($website->security_status ?: 'unknown') }}</div></div></div>
<div class="bg-white border rounded-xl p-5 mb-6"><h2 class="font-bold text-lg mb-3">Health Checks</h2><div class="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
<div class="p-3 rounded-lg {{ $website->http_code && $website->http_code < 400 ? 'bg-emerald-50' : 'bg-red-50' }}">HTTP/Connection<div class="font-bold">{{ $website->http_code ? 'HTTP '.$website->http_code : 'FAILED' }}</div></div>
<div class="p-3 rounded-lg {{ $diagnostics['content_ok'] === null ? 'bg-slate-50' : ($diagnostics['content_ok'] ? 'bg-emerald-50' : 'bg-orange-50') }}">Content Check<div class="font-bold">{{ $diagnostics['content_ok'] === null ? 'N/A' : ($diagnostics['content_ok'] ? 'PASS' : 'FAILED') }}</div></div>
<div class="p-3 rounded-lg {{ $diagnostics['integrity_status']==='ok' ? 'bg-emerald-50' : ($diagnostics['integrity_status']==='changed' ? 'bg-orange-50' : 'bg-slate-50') }}">Integrity Check<div class="font-bold">{{ strtoupper($diagnostics['integrity_status'] ?: '—') }}</div></div>
<div class="p-3 rounded-lg {{ $website->security_status==='suspicious' ? 'bg-fuchsia-50' : 'bg-slate-50' }}">Security Check<div class="font-bold">{{ strtoupper($website->security_status ?: 'unknown') }}{{ $website->security_score !== null ? ' · '.$website->security_score.'/100' : '' }}</div></div>
</div>
@if($diagnostics['status_reasons'])<h3 class="font-semibold mt-4 mb-2">Reasons</h3><ul class="list-disc ml-5 text-sm text-slate-700 space-y-1">@foreach($diagnostics['status_reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul>@endif
@if($diagnostics['first_suspicious_at'] || $diagnostics['first_failed_at'])<div class="mt-4 grid grid-cols-2 gap-3 text-xs text-slate-600"><div>First failed: <strong>{{ $diagnostics['first_failed_at']?->format('Y-m-d H:i') ?? 'never' }}</strong></div><div>First suspicious: <strong>{{ $diagnostics['first_suspicious_at']?->format('Y-m-d H:i') ?? 'never' }}</strong>{{ $diagnostics['last_suspicious_at'] ? ' · last '.$diagnostics['last_suspicious_at']->format('Y-m-d H:i') : '' }}</div></div>@endif
@if($diagnostics['baseline'])<div class="mt-4 text-xs text-slate-500">Trusted homepage baseline recorded: {{ $diagnostics['baseline']['recorded_at'] ?? '—' }} · title "{{ $diagnostics['baseline']['title'] ?? '—' }}" · HTTP {{ $diagnostics['baseline']['http_code'] ?? '—' }} · hash <code>{{ substr($diagnostics['baseline']['hash'] ?? '',0,16) }}…</code></div>@endif
</div>
<div class="grid lg:grid-cols-2 gap-6"><div class="bg-white border rounded-xl p-5"><h2 class="font-bold text-lg mb-3">What is the problem?</h2><p class="font-semibold mb-2">{{ $diagnostics['likely'] }}</p><div class="text-sm text-slate-600">{{ $diagnostics['error'] ?: 'No current error message.' }}</div><div class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="p-3 bg-slate-50 rounded-lg">DNS: <strong>{{ $diagnostics['dns_ok'] ? 'OK' : 'FAILED' }}</strong></div><div class="p-3 bg-slate-50 rounded-lg">SSL: <strong>{{ $diagnostics['ssl']['ok'] ? 'OK' : 'CHECK' }}</strong></div></div></div>
<div class="bg-white border rounded-xl p-5"><h2 class="font-bold text-lg mb-3">Quick Actions</h2><div class="space-y-2"><form method="POST" action="{{ route('websites.recheck',$website) }}">@csrf<button class="w-full text-left p-3 rounded-lg bg-blue-50 text-blue-700">🔄 Recheck website now</button></form><form method="POST" action="{{ route('websites.baseline',$website) }}" onsubmit="return confirm('Capture a NEW trusted baseline? Only do this when the website is in a known-good state.')">@csrf<button class="w-full text-left p-3 rounded-lg bg-emerald-50 text-emerald-700">📸 Capture trusted baseline (homepage + files)</button></form><form method="POST" action="{{ route('websites.security',$website) }}">@csrf<button class="w-full text-left p-3 rounded-lg bg-fuchsia-50 text-fuchsia-700">🛡 Run server file security scan</button></form><a target="_blank" href="{{ $website->url }}" class="block p-3 rounded-lg bg-slate-50">🌐 Open website</a><a href="{{ route('websites.logs',$website) }}" class="block p-3 rounded-lg bg-slate-50">📋 View monitoring history</a></div></div></div>
@if($website->security_findings)<div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">🛡 Security Findings</h2>@foreach($website->security_findings as $f)<div class="border rounded-lg p-3 mb-2 text-sm"><strong>{{ $f['reason'] ?? 'Suspicious indicator' }}</strong><div>Pattern: <code>{{ $f['pattern'] ?? '—' }}</code></div>@if(isset($f['file']))<div>File: <code>{{ $f['file'] }}</code></div>@endif</div>@endforeach</div>@endif
<div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">🛡 Security Posture</h2><div class="text-3xl font-bold mb-2">{{ $diagnostics['security_score'] ?? '—' }}<span class="text-sm text-slate-500"> / 100</span></div><p class="text-sm text-slate-500 mb-4">This is a heuristic security posture score, not a malware verdict.</p><div class="grid md:grid-cols-2 gap-2 text-xs">@foreach($diagnostics['security_headers'] ?? [] as $k=>$v)<div class="p-2 rounded bg-slate-50"><strong>{{ $k }}</strong><div class="break-all text-slate-500">{{ $v }}</div></div>@endforeach</div></div><div class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-lg mb-3">SSL Information</h2><pre class="text-xs whitespace-pre-wrap">{{ json_encode($diagnostics['ssl'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div>
@endsection
