-- Website Monitor v5 upgrade (multi-level health detection + file baselines).
-- Import ONCE on an existing v4 database. Idempotent: every statement is guarded,
-- so re-importing is safe. Does NOT delete existing websites or monitoring logs.
SET @db := DATABASE();

-- websites: content expectations + integrity/health tracking
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='expected_title'),'SELECT 1','ALTER TABLE websites ADD expected_title VARCHAR(255) NULL AFTER security_headers'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='expected_keywords'),'SELECT 1','ALTER TABLE websites ADD expected_keywords TEXT NULL AFTER expected_title'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='expected_http_code'),'SELECT 1','ALTER TABLE websites ADD expected_http_code SMALLINT UNSIGNED NULL AFTER expected_keywords'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='content_check_enabled'),'SELECT 1','ALTER TABLE websites ADD content_check_enabled TINYINT(1) NOT NULL DEFAULT 1 AFTER expected_http_code'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='file_integrity_enabled'),'SELECT 1','ALTER TABLE websites ADD file_integrity_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER content_check_enabled'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='homepage_baseline'),'SELECT 1','ALTER TABLE websites ADD homepage_baseline JSON NULL AFTER file_integrity_enabled'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='integrity_status'),'SELECT 1','ALTER TABLE websites ADD integrity_status VARCHAR(30) NOT NULL DEFAULT ''unknown'' AFTER homepage_baseline'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='last_content_ok'),'SELECT 1','ALTER TABLE websites ADD last_content_ok TINYINT(1) NULL AFTER integrity_status'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='status_reasons'),'SELECT 1','ALTER TABLE websites ADD status_reasons JSON NULL AFTER last_content_ok'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='first_suspicious_at'),'SELECT 1','ALTER TABLE websites ADD first_suspicious_at TIMESTAMP NULL AFTER status_reasons'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='websites' AND COLUMN_NAME='last_suspicious_at'),'SELECT 1','ALTER TABLE websites ADD last_suspicious_at TIMESTAMP NULL AFTER first_suspicious_at'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- monitoring_logs: per-check health details
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='monitoring_logs' AND COLUMN_NAME='content_ok'),'SELECT 1','ALTER TABLE monitoring_logs ADD content_ok TINYINT(1) NULL AFTER security_headers'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='monitoring_logs' AND COLUMN_NAME='integrity_status'),'SELECT 1','ALTER TABLE monitoring_logs ADD integrity_status VARCHAR(30) NOT NULL DEFAULT ''unknown'' AFTER content_ok'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='monitoring_logs' AND COLUMN_NAME='status_reasons'),'SELECT 1','ALTER TABLE monitoring_logs ADD status_reasons JSON NULL AFTER integrity_status'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='monitoring_logs' AND COLUMN_NAME='homepage_hash'),'SELECT 1','ALTER TABLE monitoring_logs ADD homepage_hash VARCHAR(64) NULL AFTER status_reasons'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- website_file_baselines: trusted SHA-256 baselines for important files
SET @sql := IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='website_file_baselines'),'SELECT 1','CREATE TABLE website_file_baselines (\n id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n website_id BIGINT UNSIGNED NOT NULL,\n path VARCHAR(512) NOT NULL,\n sha256 VARCHAR(64) NOT NULL,\n size BIGINT UNSIGNED NULL,\n recorded_at TIMESTAMP NULL,\n created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL,\n PRIMARY KEY(id), UNIQUE KEY website_file_baselines_website_id_path_unique(website_id,path),\n CONSTRAINT website_file_baselines_website_id_foreign FOREIGN KEY(website_id) REFERENCES websites(id) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
